import assert from 'node:assert/strict';
globalThis.Phaser={Scene:class {}};
const {ScreenReviewScene}=await import('../src/scenes/ScreenReviewScene.js');
const scene=new ScreenReviewScene();
const loaded=new Set(['gameplay-16x9']);
const requests=[];
let completion, failure;
scene.art=true;scene.mode='map';scene.section=0;
scene.scale={width:1920,height:1080};scene.input={enabled:true};
scene.textures={exists:key=>loaded.has(key)};
scene.loadingStatus=()=>{};
scene.load={on(event,fn){if(event==='loaderror')failure=fn;},off(){},once(event,fn){completion=fn;},image(key,path){requests.push({key,path});},start(){}};
let redraws=0;scene.draw=()=>redraws++;
assert.equal(scene.ensureBackground(),false);
assert.equal(scene.input.enabled,false);
assert.equal(scene.ensureBackground(),false);
assert.equal(requests.length,1,'Repeated draws must not duplicate downloads');
loaded.add(requests[0].key);completion();
assert.equal(scene.input.enabled,true);assert.equal(redraws,1);
assert.equal(scene.ensureBackground(),true);
scene.section=1;assert.equal(scene.ensureBackground(),false);
failure({key:requests[1].key});completion();
assert.equal(scene.ensureBackground(),true,'Failed background must not trigger an endless reload');
scene.mode='game';scene.level=1;scene.scale={width:1080,height:1920};
assert.equal(scene.ensureBackground(),false);
assert.equal(requests[2].key,'gameplay-9x16','Orientation switch must load the correct background');
console.log('PASS: on-demand backgrounds, duplicate guard, input restored, failure recovery, orientation change');
